"""
Content for the Contract Note Template Management walkthrough.

This is the estimate-scrubbed twin of `estimate_01.py`: the same technical
walkthrough with all commercial estimate figures removed (no effort badge, no
"Estimate 1" framing, no day counts). Factual design counts (screen count, test
properties) are retained. Kept as a standalone module (no `figures` import) so it
stays decoupled from the estimate machinery.

Draws on:
  - .kiro/specs/contract-note-template-management/{requirements,design,tasks}.md
  - analysis/BRYT/contract-note/1-pdf-me/screen-mockups.md + mockups/*.png

Build:
    python analysis/BRYT/contract-note/walkthroughs/build_walkthrough.py contract_note_template_management
"""

MOCKUPS = "1-pdf-me/mockups"

DOC = {
    "slug": "contract-note-template-management",
    "title": "Contract Note Template Management",
    "subtitle": "Technical Walkthrough",
    "date": "July 2026",
    "blocks": [
        # ---------------------------------------------------------------
        {
            "type": "section",
            "heading": "Background",
            "body": [
                "Contract notes are the PDF documents BRYT Energy produces when a customer signs up to an "
                "energy contract. Today they are generated by a fixed pipeline: an XML file lands in S3, a "
                ".NET SVG engine renders it to HTML, and that HTML is converted to a PDF. Any change to the "
                "layout, wording, or terms means a developer has to edit and redeploy code.",
                "That makes the current system slow to change and entirely developer-dependent. Business "
                "users cannot adjust a template, add a new contract type, or update Terms & Conditions "
                "without raising a development request.",
                "This work replaces the rendering mechanism with a self-service template management system "
                "inside the existing BrytAdminPortal. Business users compose templates visually, define the "
                "rules that pick the right template automatically, and manage reusable content like headers, "
                "footers, and T&Cs, all without developer involvement. The S3-triggered entry point stays the "
                "same, so upstream systems are unaffected.",
            ],
        },
        {
            "type": "callout",
            "heading": "What changes, in one line",
            "body": [
                "The trigger and the output stay the same (XML in, PDF out). What changes is the middle: a "
                "hard-coded .NET renderer becomes a business-managed library of templates and sections, "
                "rendered by pdf-me and stitched with pdf-lib.",
            ],
        },
        {
            "type": "callout",
            "heading": "Updated after the client playback",
            "body": [
                "Following the client playback, three refinements are folded in: (1) section version "
                "changes are published to linked templates explicitly rather than taking effect automatically; "
                "(2) a section can hold multiple rule-driven variants, so one slot renders different content "
                "depending on the contract data; and (3) the render pipeline is orchestrated as a Step Functions "
                "state machine with per-section processing. The management screens remain full landing pages, "
                "with the visual editor and version history as modals launched from them.",
            ],
        },
        # ---------------------------------------------------------------
        {
            "type": "section",
            "heading": "How it works",
            "pageBreak": True,
            "body": [
                "The system has two halves. The first is a management experience in the Admin Portal where "
                "users build and maintain templates. The second is an automated render pipeline that runs "
                "when contract data arrives and produces the finished PDF.",
                "A template is an ordered set of sections. Each section is a small pdf-me layout (positioned "
                "text, multi-variable text, and tables). Sections render independently and are then stitched "
                "into one document. Common content, headers, footers, and Terms & Conditions, lives as "
                "shared sections that can be reused across many templates.",
                "When contract data arrives, the pipeline decides which template to use by evaluating each "
                "template's selection rule in priority order and taking the first match. It then renders that "
                "template's sections and stitches them into the final PDF.",
            ],
        },
        {
            "type": "table",
            "heading": "The moving parts",
            "intro": "Five components make up the solution. The first three are user-facing; the last two run automatically.",
            "columns": ["Component", "Where it lives", "What it does"],
            "rows": [
                ["Template management UI", "Angular module in BrytAdminPortal",
                 "CRUD for templates, sections, and shared sections; drag-to-reorder priority and composition"],
                ["Rules engine UI", "Angular module in BrytAdminPortal",
                 "Visual tree editor for the selection rule that picks a template automatically"],
                ["Section editor", "Embedded pdf-me Designer (React web component)",
                 "Visual field placement on a base PDF, opened in a modal"],
                ["Render pipeline", "AWS Step Functions state machine",
                 "Parses data, selects a template, then renders each section (with variant selection) in a per-section Map state, and stitches with pdf-lib"],
                ["Storage", "DynamoDB + S3",
                 "DynamoDB holds template/section/variant metadata and rules; S3 holds the schema JSON and output PDFs"],
            ],
        },
        {
            "type": "layers",
            "heading": "System architecture",
            "body": [
                "The Admin Portal talks to a set of Lambda APIs for templates, sections, and rules, backed by "
                "DynamoDB (metadata) and S3 (schema JSON). The render pipeline is triggered by an XML drop in "
                "S3, reads the same metadata and schema, and writes the finished PDF to the output bucket.",
            ],
            "lanes": [
                {"label": "Admin Portal (Angular)",
                 "nodes": ["Template List", "Template Edit", "Rules & Variants", "Section Editor", "Shared Sections"]},
                {"label": "Lambda APIs",
                 "nodes": ["Template API", "Section API", "Rules API"]},
                {"label": "Storage",
                 "nodes": ["DynamoDB - metadata & rules", "S3 - schema JSON & output PDFs"]},
                {"label": "Render (Step Functions)",
                 "nodes": ["Parse", "Select Template", "Render Sections (Map)", "Stitch", "Write PDF"]},
            ],
            "caption": "Admin Portal (top) manages content; APIs persist it; the Step Functions render pipeline consumes the same storage.",
        },
        {
            "type": "pipeline",
            "heading": "Render pipeline flow",
            "body": [
                "When an XML file lands in the input bucket, a Step Functions state machine runs the flow: "
                "parse the data, pick the template by evaluating rules in priority order, then render each "
                "section in a per-section Map state (resolving its pinned version and selecting the matching "
                "variant), stitch them into one PDF, and write the result out.",
            ],
            "steps": [
                "XML lands in S3",
                "Parse to JSON",
                "Select template (rules, first match)",
                "Render sections (Map: variant + pdf-me)",
                "Stitch PDF (pdf-lib)",
                "Write PDF to S3",
            ],
            "caption": "Each section renders as an independent, retryable step. A failure after retries routes to a "
                       "failure state, logs an error record, and writes no partial PDF.",
        },
        # ---------------------------------------------------------------
        {
            "type": "table",
            "heading": "Key design decisions",
            "pageBreak": True,
            "intro": "The design settled on a handful of choices that shape the rest of the build.",
            "columns": ["Decision", "Choice", "Why"],
            "rows": [
                ["Templates", "Ordered list of sections",
                 "Sections render independently, so dynamic content (like multi-page tables) is handled cleanly, then stitched"],
                ["Shared content", "Reusable shared sections",
                 "Headers, footers, and T&Cs are defined once and referenced, not copied. Edit once, applies everywhere"],
                ["T&Cs", "Just shared sections, positioned last",
                 "No special upload mechanism; T&Cs use the same editor and are always placed at the end"],
                ["Selection rules", "Specification pattern (rule tree)",
                 "AND/OR/NOT logic with EQUALS/IN/LESS_THAN/MORE_THAN leaves; first match by priority wins"],
                ["Section variants", "Ordered variants, each with a rule + default",
                 "One section slot can render alternatives; reuses the same rule engine; first matching variant wins"],
                ["Version publishing", "Pinned version per template link",
                 "A section edit creates a new version but only goes live when explicitly published to linked templates"],
                ["Editor embedding", "pdf-me Designer as a web component",
                 "Wraps the React designer as a custom element, embedded in Angular via a modal; avoids a bridge library"],
                ["Storage", "DynamoDB single-table + S3",
                 "Fast ordered queries for metadata; S3 is cost-effective for the larger schema JSON blobs"],
                ["Pipeline", "Step Functions state machine (per-section Map)",
                 "Isolates and retries each section's variant selection + render; handles many-section documents; better observability"],
            ],
        },
        # ---------------------------------------------------------------
        {
            "type": "screens",
            "heading": "Screen-by-screen walkthrough",
            "pageBreak": True,
            "intro": "Six screens make up the template management experience. Screens 1, 2 and 5 are full landing "
                     "pages reached from the Admin Portal navigation; screens 4 and 6 are modals launched from within "
                     "them. Each is shown below with the user interactions it supports and the data model behind it.",
            "screens": [
                {
                    "image": f"{MOCKUPS}/01-template-list.png",
                    "title": "1. Template List (landing page)",
                    "body": [
                        "The entry point: a full landing page listing every previously configured template in an "
                        "ordered table. The order is meaningful, it is the priority in which selection rules are "
                        "evaluated at render time.",
                    ],
                    "interactions": [
                        "Drag the handle to reorder priority (top = evaluated first)",
                        "Rules button opens the rule tree editor for that template",
                        "Edit opens the template composition screen",
                        "Delete prompts for confirmation before removing",
                        "Create Template adds a new template at the lowest priority",
                    ],
                    "data": [
                        "Each row is a Template record in DynamoDB (name, description, sectionCount, priority)",
                        "Ordering is a query on the PriorityIndex GSI (all templates, sorted by priority)",
                        "Reordering rewrites priority values to stay contiguous (1..N)",
                        "Deleting re-numbers the remaining templates to keep priorities contiguous",
                    ],
                },
                {
                    "image": f"{MOCKUPS}/02-template-edit.png",
                    "title": "2. Template Edit (landing page)",
                    "body": [
                        "Where a template's metadata and section composition are managed. The centre panel is the "
                        "ordered section list; the right panel adds new or shared sections; the bottom panel is the "
                        "change log. Sections with variants show their variants inline on this page.",
                    ],
                    "interactions": [
                        "Drag to reorder sections within the template",
                        "Edit in Designer opens the pdf-me section editor",
                        "History opens the version history (and the publish action) for that section",
                        "Add Shared Section picks from the shared library; T&Cs auto-position at the end",
                        "Expand a section to manage its variants (add, reorder, set default, edit each variant's rule)",
                        "A version badge (e.g. v3) plus an 'update available' hint shows the pinned version state",
                    ],
                    "data": [
                        "Sections are Section records keyed by sortOrder within the template",
                        "Shared sections are stored as references (sharedSectionId), never duplicated",
                        "A reference records the pinned version the template resolves to at render time",
                        "Variants are Section Variant records, each with its own rule and version history",
                        "Every change writes a Template Change Log record (who, what, when)",
                    ],
                },
                {
                    "image": f"{MOCKUPS}/03-rules-config.png",
                    "title": "3. Rules Configuration",
                    "body": [
                        "The visual editor for a template's selection rule. The rule is a specification tree: logical "
                        "operators (AND, OR, NOT) combining comparison leaves (EQUALS, IN, LESS_THAN, MORE_THAN). "
                        "The same editor is reused to configure a section variant's rule.",
                    ],
                    "interactions": [
                        "Click a node to select it and edit it in the right panel",
                        "Add logical operators or comparisons as children of the selected node",
                        "Delete removes a node and its children",
                        "Save validates the tree is well-formed before persisting",
                    ],
                    "data": [
                        "Serialised as a JSON tree on the template's Rule record",
                        "AND/OR nodes have leftOperand + rightOperand; NOT has a single operand",
                        "Leaves reference a data field (e.g. offer.producttype) and a value or value set",
                        "Validation rejects incomplete nodes and reports their location",
                    ],
                },
                {
                    "image": f"{MOCKUPS}/04-section-editor.png",
                    "title": "4. Section Editor (pdf-me Designer)",
                    "body": [
                        "The pdf-me visual designer, embedded in a modal. Fields are positioned on a base PDF "
                        "background, giving users a true what-you-see layout experience.",
                    ],
                    "interactions": [
                        "Drag fields on the canvas to reposition them",
                        "Click a field to edit its properties (position, size, font, alignment)",
                        "Add text, multi-variable text, or table fields from the toolbar",
                        "Undo/redo; Save writes the layout back",
                    ],
                    "data": [
                        "Each section's layout is a pdf-me Schema JSON blob stored in S3",
                        "The schemas array holds one entry per page of the section",
                        "Saving creates a new version rather than overwriting (see screen 6)",
                        "The same editor is used for regular, shared, and T&C sections",
                    ],
                },
                {
                    "image": f"{MOCKUPS}/05-shared-sections.png",
                    "title": "5. Shared Sections Library",
                    "body": [
                        "Manages reusable sections, headers, footers, and Terms & Conditions. Each shows how many "
                        "templates use it, and the detail panel lists exactly which ones.",
                    ],
                    "interactions": [
                        "Select a shared section to see its detail and where it is used",
                        "Edit in Designer opens the same pdf-me editor",
                        "Delete warns (and lists templates) if the section is still referenced",
                        "Create prompts for a name and type (standard or T&C)",
                    ],
                    "data": [
                        "Shared Section records are keyed separately from templates",
                        "A Reference record links each shared section to the templates using it",
                        "Editing a shared section propagates to every template that references it",
                        "Deletion is blocked while references exist",
                    ],
                },
                {
                    "image": f"{MOCKUPS}/06-version-history.png",
                    "title": "6. Section Version History (modal)",
                    "body": [
                        "Every save of a section creates a new version, so nothing is ever lost. This modal lists "
                        "the versions, lets a user preview or revert to an earlier one, and publishes a chosen "
                        "version out to the templates linked to that section.",
                    ],
                    "interactions": [
                        "The current version is highlighted at the top",
                        "View in Designer opens the current version read-only",
                        "Preview opens a historical version read-only",
                        "Revert creates a new version from the selected one (non-destructive)",
                        "Publish pushes a chosen version (latest by default) to all linked templates",
                    ],
                    "data": [
                        "Each save writes a Section Version record (timestamp, user, schema location)",
                        "Reverting copies an old version forward as a new version; intermediate versions remain",
                        "Publishing updates the pinned version on every linked template's reference",
                        "All versions are retained indefinitely (no automatic purging)",
                    ],
                },
            ],
        },
        # ---------------------------------------------------------------
        {
            "type": "section",
            "heading": "The rules engine, in plain terms",
            "pageBreak": True,
            "body": [
                "The rules engine decides which template to use for a given contract without anyone choosing "
                "manually. Each template carries a rule; at render time the pipeline evaluates rules in the "
                "priority order from the template list and uses the first one that matches.",
                "A rule is a tree. Branches are logical operators (AND, OR, NOT) and leaves are comparisons "
                "against fields in the contract data. For example: producttype EQUALS 'Fixed' AND (region IN "
                "[North, South] OR mpancount MORE_THAN 5).",
            ],
            "bullets": [
                "EQUALS - the field exactly matches a value",
                "IN - the field is one of a set of values",
                "LESS_THAN / MORE_THAN - numeric comparison against a threshold",
                "AND / OR / NOT - combine or negate the above",
            ],
        },
        {
            "type": "callout",
            "heading": "First match wins",
            "body": [
                "Because rules are evaluated in priority order and the first match is taken, template ordering is "
                "a real business lever. More specific templates sit higher; a general fallback sits at the bottom. "
                "If nothing matches, the pipeline logs an error rather than guessing.",
            ],
        },
        # ---------------------------------------------------------------
        {
            "type": "table",
            "heading": "Data model at a glance",
            "intro": "Everything lives in a single DynamoDB table using a PK/SK pattern, with the larger layout blobs in S3.",
            "columns": ["Record", "Holds", "Notes"],
            "rows": [
                ["Template", "Name, description, priority, section count", "One per template; ordered via a priority GSI"],
                ["Section", "Name, sort order, shared reference, pinned version", "Owned by a template; ordered by sortOrder"],
                ["Section Variant", "Name, order, default flag, rule, schema location", "Ordered variants within a section; first matching rule wins"],
                ["Shared Section", "Name, T&C flag, schema location", "Reusable; referenced by many templates"],
                ["Reference", "Template link + pinned version", "Tracks which templates use a section and the version each resolves to"],
                ["Section Version", "Timestamp, user, schema location", "One per save, per variant; enables history, revert, publish"],
                ["Rule", "Specification tree JSON", "Drives template selection and variant selection"],
                ["Change Log", "Change type, description, user, time", "Audit trail of template changes"],
                ["Schema JSON (S3)", "pdf-me field layout per section/variant", "Referenced by sections, variants, and versions"],
            ],
        },
        # ---------------------------------------------------------------
        {
            "type": "table",
            "heading": "Delivery breakdown",
            "pageBreak": True,
            "intro": "The build is grouped into the following areas.",
            "columns": ["Area", "Scope"],
            "rows": [
                ["Infrastructure & types", "DynamoDB table + GSI, S3 buckets, API Gateway routes, Step Functions state machine, shared TypeScript types, rule validation"],
                ["Template API", "List, create, get, update, delete, reorder handlers with priority management"],
                ["Section API", "Section CRUD, schema get/save, version history + revert, version publishing, variant CRUD + variant rules, shared section CRUD, change log"],
                ["Rules API", "Get and save the specification tree, with validation"],
                ["Render pipeline", "Step Functions orchestration, rule evaluator, template selection, per-section variant selection, pinned-version resolution, section renderer, PDF stitcher, XML-to-JSON + S3 trigger"],
                ["Angular frontend", "Template list, template edit, rules config, section editor web component, shared sections, version history, section variants, version publishing, navigation/landing pages"],
                ["Integration", "CDK wiring, IAM, S3-triggered state machine, portal navigation, end-to-end validation"],
            ],
        },
        {
            "type": "callout",
            "heading": "Testing note",
            "body": [
                "The build is designed around 38 correctness properties (ordering, round-trips, rule and variant "
                "evaluation, version publishing, per-section failure isolation, "
                "PDF page-count preservation, and so on). Property-based and integration tests are marked optional "
                "in the plan and can be deferred for a faster MVP, but they are recommended given the pipeline's "
                "role in producing legally significant documents.",
            ],
        },
    ],
}
